### PR TITLE
Fix viewport comment

### LINKED ISSUE #41: VRViewport coordinates are ints or floats?
According to the docs, `VRViewport` coordinates are given as floats. https://github.com/servo/rust-webvr/blob/4e3099913d82883eedeaecfd568f34f6ebf01d58/rust-webvr-api/src/vr_framebuffer.rs#L11-L13

According to the implementation, they're ints. https://github.com/servo/rust-webvr/blob/4e3099913d82883eedeaecfd568f34f6ebf01d58/rust-webvr-api/src/vr_framebuffer.rs#L36-L41

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #41

### CODE REVIEW

File: rust-webvr-api/src/vr_framebuffer.rs [hunk 1]
```diff
@@ -8,8 +8,8 @@ pub struct VRFramebuffer {
     /// The attributes set up for this framebuffer
     pub attributes: VRFramebufferAttributes,
 
-    /// UVs defining the texture bounds to present to the eye in UV space: [x,y,w,h]
-    /// Defaults to [0.0, 0.0, 0.5, 1.0]
+    /// The 2D rectangle that should be used to project the 3D scene
+    /// to the position of the eye camera. Measured in pixels.
```
Comment (asajeffrey) [inline rust-webvr-api/src/vr_framebuffer.rs]: Nit: `device pixels` (browsers have lots of competing ideas about what a pixel is, sigh).

Comment (MortimerGoro) [reply rust-webvr-api/src/vr_framebuffer.rs]: done
